spring:
  application:
    name: gateway-server
  main:
    web-application-type: reactive

  # Config Server 연결
  config:
    import: "optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}"

  # Cloud
  cloud:
    config:
      uri: ${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
      username: ${SPRING_CLOUD_CONFIG_USERNAME:config}
      password: ${SPRING_CLOUD_CONFIG_PASSWORD:config123}
      fail-fast: false
      retry:
        initial-interval: 3000
        max-attempts: 6
        max-interval: 4000
        multiplier: 1.1
    compatibility-verifier:
      enabled: false

server:
  port: 8070


management:
  endpoints:
    enabled-by-default: false

logging:
  level:
    org.springframework.cloud.gateway: INFO
    com.muscat.gateway: INFO