spring:
  application:
    name: gateway-server
  config:
    import:
      - "optional:aws-secretsmanager:ggeolmuse/production"
      - "optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://config-server:8888}"
  cloud:
    config:
      uri: ${SPRING_CLOUD_CONFIG_URI:http://config-server:8888}
      username: ${SPRING_CLOUD_CONFIG_USERNAME:config}
      password: ${SPRING_CLOUD_CONFIG_PASSWORD:config123}

server:
  port: 8070
