spring:
  application:
    name: "gateway-server"
  config:
    import: "optional:configserver:http://config-server:8888/"
  main:
    web-application-type: reactive
  cloud:
    config:
      username: ${SPRING_CLOUD_CONFIG_USERNAME:config}
      password: ${SPRING_CLOUD_CONFIG_PASSWORD:config123}
    kubernetes:
      discovery:
        enabled: false
    discovery:
      client:
        health-indicator:
          enabled: false
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 10s
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

server:
  port: 8070

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted

services:
  market-data:
    uri: http://market-data-service:8083
  user:
    uri: http://user-service:8080
  trade:
    uri: http://trade-service:8081
  backtest:
    uri: http://backtest-service:8082
