{{- if .Values.services.backtestService.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.backtestService.name }}
  labels:
    app: {{ .Values.services.backtestService.name }}
    {{- include "ggeolmuse.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.backtestService.service.type }}
  ports:
  - name: http
    port: {{ .Values.services.backtestService.service.port }}
    targetPort: {{ .Values.services.backtestService.service.port }}
    protocol: TCP
  - name: management
    port: 9090
    targetPort: 9090
    protocol: TCP
  selector:
    app: {{ .Values.services.backtestService.name }}
{{- end }}
