spring:
  application:
    name: market-data-service

  # Config Server 연결
  config:
    import: "optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://config-server:8888}"

  cloud:
    config:
      uri: ${SPRING_CLOUD_CONFIG_URI:http://config-server:8888}
      username: ${SPRING_CLOUD_CONFIG_USERNAME:config}
      password: ${SPRING_CLOUD_CONFIG_PASSWORD:config123}
      fail-fast: false
      retry:
        initial-interval: 3000
        max-attempts: 6

  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis.default.svc.cluster.local}
      port: 6379


## Server port moved to Config Server
