-- Asset table
CREATE TABLE IF NOT EXISTS asset (
    symbol VARCHAR(16) PRIMARY KEY,
    name VARCHAR(256) NOT NULL,
    country VARCHAR(3) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    asset_type VARCHAR(16) NOT NULL,
    market_cap BIGINT,
    active BOOLEAN NOT NULL DEFAULT true,
    delisted_date DATE
);

-- Performance indexes for asset table
CREATE INDEX IF NOT EXISTS idx_asset_market_cap ON asset(market_cap DESC NULLS LAST);
CREATE INDEX IF NOT EXISTS idx_asset_active ON asset(active) WHERE active = true;

-- Candle table
CREATE TABLE IF NOT EXISTS candle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol VARCHAR(16) NOT NULL,
    date DATE NOT NULL,
    currency VARCHAR(3) NOT NULL,
    open DECIMAL(19,8),
    high DECIMAL(19,8),
    low DECIMAL(19,8),
    close DECIMAL(19,8),
    volume BIGINT,
    adjusted_close DECIMAL(19,8) NOT NULL,
    dividend_amount DECIMAL(19,8) NOT NULL DEFAULT 0,
    split_coefficient DECIMAL(19,8) NOT NULL DEFAULT 1,
    UNIQUE(symbol, date, currency)
);

CREATE INDEX IF NOT EXISTS idx_candle_symbol_date ON candle(symbol, date);

CREATE TABLE IF NOT EXISTS dividend (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol VARCHAR(16) NOT NULL,
    ex_date DATE NOT NULL,
    amount DECIMAL(19,8) NOT NULL,
    currency VARCHAR(3) NOT NULL DEFAULT 'USD',
    UNIQUE(symbol, ex_date)
);

-- FX rate table
CREATE TABLE IF NOT EXISTS fx_rate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    currency_pair VARCHAR(7) NOT NULL,
    date DATE NOT NULL,
    rate DECIMAL(10,6) NOT NULL,
    UNIQUE(currency_pair, date)
);
