plugins {
    id 'org.springframework.boot' version '3.5.4' apply false
    id 'io.spring.dependency-management' version '1.1.7' apply false
}

allprojects {
    group = 'com.muscat'
    version = '0.0.1-SNAPSHOT'

    repositories {
        mavenCentral()
    }
}

subprojects {
    repositories { mavenCentral() }
    
    apply plugin: 'io.spring.dependency-management'
    
    dependencyManagement {
        dependencies {
            dependency 'com.querydsl:querydsl-jpa:5.0.0'
            dependency 'com.querydsl:querydsl-apt:5.0.0'
        }
    }

    plugins.withType(org.gradle.api.plugins.JavaPlugin).configureEach {
        extensions.getByType(JavaPluginExtension).toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
        
        // UTF-8 인코딩 설정
        tasks.withType(JavaCompile).configureEach {
            options.encoding = 'UTF-8'
        }
        
        tasks.withType(Test).configureEach { 
            useJUnitPlatform()
            systemProperty 'file.encoding', 'UTF-8'
        }
    }
}
