plugins {
    id 'org.springframework.boot' version '3.5.4' apply false
    id 'io.spring.dependency-management' version '1.1.7' apply false
}

allprojects {
    group = 'com.muscat'
    version = '0.0.1-SNAPSHOT'

    repositories {
        mavenCentral()
    }
}

subprojects {
    repositories { mavenCentral() }

    plugins.withType(org.gradle.api.plugins.JavaPlugin).configureEach {
        extensions.getByType(JavaPluginExtension).toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
        tasks.withType(Test).configureEach { useJUnitPlatform() }
    }
}
