<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.muscat</groupId>
    <artifactId>ggeolmuse-backend</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <name>GGeolmuse Backend</name>
    <description>백엔드 모듈을 한 번에 여는 애그리게이터</description>

    <modules>
        <module>ggeolmuse-bom</module>
        <module>messaging</module>
        <module>config-server</module>
        <module>gateway-server</module>
        <module>market-data-service</module>
        <module>trade-service</module>
        <module>user-service</module>
        <module>backtest-service</module>
    </modules>
</project>
