{{- if .Values.services.tradeService.enabled }}
{{- include "ggeolmuse.serviceAccount" (dict "name" .Values.services.tradeService.name "Values" .Values) }}
---
{{- include "ggeolmuse.javaDeployment" (dict "svc" .Values.services.tradeService "Values" .Values "Chart" .Chart "Release" .Release) }}
{{- end }}
