-- ============================================================
-- 테이블
-- ============================================================

-- 자산 테이블
CREATE TABLE IF NOT EXISTS asset (
    symbol VARCHAR(16) PRIMARY KEY,
    name VARCHAR(256) NOT NULL,
    country VARCHAR(3) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    asset_type VARCHAR(16) NOT NULL,
    market_cap BIGINT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    delisted_date DATE
);

-- 캔들 테이블
CREATE TABLE IF NOT EXISTS candle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol VARCHAR(16) NOT NULL,
    date DATE NOT NULL,
    currency VARCHAR(3) NOT NULL,
    open DECIMAL(19,8),
    high DECIMAL(19,8),
    low DECIMAL(19,8),
    close DECIMAL(19,8),
    volume BIGINT,
    adjusted_close DECIMAL(19,8) NOT NULL,
    dividend_amount DECIMAL(19,8) NOT NULL DEFAULT 0,
    split_coefficient DECIMAL(19,8) NOT NULL DEFAULT 1,
    UNIQUE(symbol, date, currency)
);

-- 배당 테이블
CREATE TABLE IF NOT EXISTS dividend (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol VARCHAR(16) NOT NULL,
    ex_date DATE NOT NULL,
    amount DECIMAL(19,8) NOT NULL,
    currency VARCHAR(3) NOT NULL DEFAULT 'USD',
    UNIQUE(symbol, ex_date)
);

-- 환율 테이블
CREATE TABLE IF NOT EXISTS fx_rate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    currency_pair VARCHAR(7) NOT NULL,
    date DATE NOT NULL,
    rate DECIMAL(10,6) NOT NULL,
    UNIQUE(currency_pair, date)
);

-- ============================================================
-- 인덱스
-- ============================================================

-- 1. Candle 테이블 인덱스
-- 기간별 OHLC 조회 최적화 (getMultipleOHLCPrices - findBySymbolsAndDateRange)
CREATE INDEX idx_candle_symbol_date ON candle(symbol, date);

-- 최신 가격 조회 최적화 (getCurrentPrice - findFirstBySymbolOrderByDateDesc)
CREATE INDEX idx_candle_symbol_date_desc ON candle(symbol, date DESC);

-- 배당 포함 캔들 조회 최적화 (getCandlesWithDividends)
CREATE INDEX idx_candle_dividend_lookup ON candle(symbol, date, dividend_amount);

-- 2. Asset 테이블 인덱스
-- 국가별 자산 조회 최적화 (getAssetsByCountry)
CREATE INDEX idx_asset_country ON asset(country);

-- 통화별 자산 조회 최적화 (getAssetsByCurrency)
CREATE INDEX idx_asset_currency ON asset(currency);

-- 자산 유형별 조회 최적화 (getAssetsByType)
CREATE INDEX idx_asset_type ON asset(asset_type);

-- 동적 필터링 최적화 (getAssetsWithFilters)
CREATE INDEX idx_asset_filters ON asset(country, currency, asset_type);

-- 3. Dividend 테이블 인덱스
-- 기간별 배당 조회 최적화 (getDividendHistory - findBySymbolsAndDateRange)
CREATE INDEX idx_dividend_symbol_date ON dividend(symbol, ex_date);

-- 고배당주 검색 최적화 (findHighDividendStocks)
CREATE INDEX idx_dividend_amount_date ON dividend(amount DESC, ex_date);

-- 배당 지급일 조회 최적화
CREATE INDEX idx_dividend_ex_date ON dividend(ex_date);

-- 4. FX Rate 테이블 인덱스
-- 날짜별 환율 조회 최적화 (findByDate)
CREATE INDEX idx_fx_rate_date ON fx_rate(date);

-- 최신 환율 조회 최적화 (findLatestRate)
CREATE INDEX idx_fx_rate_date_desc ON fx_rate(date DESC);

-- 기간별 환율 조회 최적화 (findByDateRange)
CREATE INDEX idx_fx_rate_date_range ON fx_rate(date, currency_pair);

-- Asset 활성 상태 인덱스
CREATE INDEX IF NOT EXISTS idx_asset_active ON asset(active);
CREATE INDEX IF NOT EXISTS idx_asset_active_filters ON asset(active, country, asset_type);
