-- 역분할이 쌓인 종목은 조정된 과거가가 10^11 을 넘는다(UVXY 등). 정밀도만 올려 테이블은 다시 쓰지 않는다
ALTER TABLE candle ALTER COLUMN open SET DATA TYPE NUMERIC(24,8);
ALTER TABLE candle ALTER COLUMN high SET DATA TYPE NUMERIC(24,8);
ALTER TABLE candle ALTER COLUMN low SET DATA TYPE NUMERIC(24,8);
ALTER TABLE candle ALTER COLUMN close SET DATA TYPE NUMERIC(24,8);
ALTER TABLE candle ALTER COLUMN adjusted_close SET DATA TYPE NUMERIC(24,8);
