---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backtest-service
  labels:
    app: backtest-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backtest-service
  template:
    metadata:
      labels:
        app: backtest-service
        tier: business-service
    spec:
      containers:
      - name: backtest-service
        image: muscathan/backtest-service:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        env:
        - name: SERVER_PORT
          value: "8082"
        - name: SPRING_PROFILES_ACTIVE
          value: "dev,no-file-logging"
        - name: SPRING_APPLICATION_NAME
          value: "backtest-service"
        - name: SPRING_REDIS_HOST
          value: "redis"
        - name: SPRING_REDIS_PORT
          value: "6379"
        - name: MANAGEMENT_HEALTH_REDIS_ENABLED
          value: "false"
        - name: KEYCLOAK_AUTH_SERVER_URL
          value: "http://keycloak:8080"
        - name: KEYCLOAK_REALM
          value: "muscathan"
        - name: KEYCLOAK_SECRET
          valueFrom:
            secretKeyRef:
              name: ggeolmuse-secrets
              key: KEYCLOAK_SECRET
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 120
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: backtest-service
  labels:
    app: backtest-service
spec:
  type: ClusterIP
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
  selector:
    app: backtest-service