{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ggeolmuse.fullname" . }}-monitoring-ingress
  namespace: monitoring
  labels:
    {{- include "ggeolmuse.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .host }}
    http:
      paths:
      {{- range .paths }}
      {{- if .backend.namespace }}
      - path: {{ .path }}
        pathType: {{ .pathType }}
        backend:
          service:
            name: {{ .backend.service }}
            port:
              number: {{ .backend.port }}
      {{- end }}
      {{- end }}
  {{- end }}
{{- end }}
