{{- if .Values.ingress.enabled }}
---
# Grafana Service
apiVersion: v1
kind: Service
metadata:
  name: prometheus-grafana-proxy
  namespace: default
  labels:
    {{- include "ggeolmuse.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
---
# Grafana Endpoints
apiVersion: v1
kind: Endpoints
metadata:
  name: prometheus-grafana-proxy
  namespace: default
  labels:
    {{- include "ggeolmuse.labels" . | nindent 4 }}
subsets:
  - addresses:
      - ip: 10.43.157.176
    ports:
      - name: http
        port: 80
        protocol: TCP
{{- end }}
