apiVersion: v2
name: ggeolmuse
description: GGeolmuse - 마이크로서비스 아키텍처
type: application

version: 1.0.0
appVersion: "1.2.3"

keywords:
  - trading
  - microservices
  - spring-boot
  - react
  - kubernetes

maintainers:
  - name: GGeolmuse Team
    email: contact@ggeolmuse.com
