spring:
  application:
    name: user-service

  # Cloud
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: false
  datasource:
    url: jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

# Keycloak 설정
keycloak:
  auth-server-url: http://keycloak:8080
  realm: master
  resource: muscat-user-cc
  credentials:
    secret: 2kE3bSRRdpArSzS9lDmbVImJfSbqIT6J
  admin:
    username: admin
    password: admin

app:
  exchange-rate:
    min-valid-rate: 1000
    max-valid-rate: 1500
    fallback-rate: 1300
  oauth:
    redirect-uri: http://localhost:8070/oauth/callback