spring:
  datasource:
    url: jdbc:h2:mem:tradedb
    username: sa
    password:

# Keycloak Trade Service 전용 설정  
keycloak:
  resource: muscathan-trade-cc
  credentials:
    secret: ${KEYCLOAK_SECRET}