server:
  port: 8080

spring:
  application:
    name: user-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}

# Keycloak 설정
keycloak:
  resource: ggeolmuse-client
  credentials:
    secret: ${KEYCLOAK_SECRET}

# 로깅 설정
logging:
  level:
    com.muscat.user: INFO