-- 사용자 테이블
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255),
    nickname VARCHAR(255),
    keycloak_id VARCHAR(255),
    provider VARCHAR(50) NOT NULL DEFAULT 'LOCAL',
    role VARCHAR(50) NOT NULL DEFAULT 'USER',
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    last_login_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    social_id VARCHAR(255),
    social_email VARCHAR(255),
    profile_image_url VARCHAR(500)
);

-- 계좌 테이블
CREATE TABLE IF NOT EXISTS account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    account_number VARCHAR(20) UNIQUE NOT NULL,
    account_name VARCHAR(50) NOT NULL,
    balance_krw DECIMAL(15,0) NOT NULL DEFAULT 0,
    balance_usd DECIMAL(15,2) NOT NULL DEFAULT 0,
    total_exchanged_krw DECIMAL(15,0) NOT NULL DEFAULT 0,
    avg_exchange_rate DECIMAL(10,6) NOT NULL DEFAULT 0,
    commission_rate DECIMAL(6,5) NOT NULL DEFAULT 0,
    slippage_rate DECIMAL(6,5) NOT NULL DEFAULT 0.01,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_account_user_id ON account(user_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_account_number ON account(account_number);

-- 계좌 거래 내역 테이블
CREATE TABLE IF NOT EXISTS account_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    transaction_type VARCHAR(20) NOT NULL,
    amount DECIMAL(15,2) NOT NULL,
    currency VARCHAR(3),
    balance_after DECIMAL(15,2),
    description VARCHAR(500),
    reference_id VARCHAR(100),
    created_at TIMESTAMP NOT NULL,
    from_currency VARCHAR(3),
    to_currency VARCHAR(3),
    exchange_rate DECIMAL(10,6),
    original_amount DECIMAL(15,2),
    FOREIGN KEY (account_id) REFERENCES account(id) ON DELETE CASCADE
);

-- 이메일 인증 토큰 테이블
CREATE TABLE IF NOT EXISTS email_verification_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(255) UNIQUE NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    expiry_date TIMESTAMP NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 비밀번호 재설정 토큰 테이블
CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(255) UNIQUE NOT NULL,
    user_id BIGINT NOT NULL,
    expiry_date TIMESTAMP NOT NULL,
    used BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_password_reset_token ON password_reset_tokens(token);
CREATE INDEX IF NOT EXISTS idx_password_reset_user_id ON password_reset_tokens(user_id);

-- 성능 최적화를 위한 추가 인덱스
-- USERS: 이메일 고유 (already covered by UNIQUE constraint)
-- ACCOUNT_HISTORY: 참조ID(멱등키) 고유
CREATE UNIQUE INDEX IF NOT EXISTS ux_acct_hist_reference ON account_history(reference_id);

-- ACCOUNT_HISTORY: 계정+시간 조회용
CREATE INDEX IF NOT EXISTS ix_acct_hist_acc_time ON account_history(account_id, created_at);

-- ACCOUNT: 같은 유저 안에서 계좌명 중복 방지
CREATE UNIQUE INDEX IF NOT EXISTS ux_account_user_name ON account(user_id, account_name);
