-- 참고용 스냅샷
-- 스키마를 바꾸는 것은 db/migration 뿐이다. 마이그레이션을 더할 때 이 파일도 같이 고친다.
--
-- V1 ~ V5 를 적용한 결과다. 운영 DB 한 곳만 다르다 — idx_asset_active 가
-- WHERE active = true 가 붙은 부분 인덱스다. 마이그레이션 이전에 만들어진 것이라 그대로 둔다.

-- ============================================================
-- 테이블
-- ============================================================

-- 자산
CREATE TABLE asset (
    symbol        VARCHAR(16) PRIMARY KEY,
    name          VARCHAR(256) NOT NULL,
    country       VARCHAR(3)   NOT NULL,
    currency      VARCHAR(3)   NOT NULL,
    asset_type    VARCHAR(16)  NOT NULL,
    market_cap    BIGINT,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    delisted_date DATE,
    -- 요약 조회가 쓰는 최신 캔들 값 (V5)
    latest_close  DECIMAL(19,8),
    latest_date   DATE
);

-- 일봉
CREATE TABLE candle (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol            VARCHAR(16)  NOT NULL,
    date              DATE         NOT NULL,
    currency          VARCHAR(3)   NOT NULL,
    open              DECIMAL(19,8),
    high              DECIMAL(19,8),
    low               DECIMAL(19,8),
    close             DECIMAL(19,8),
    volume            BIGINT,
    adjusted_close    DECIMAL(19,8) NOT NULL,
    dividend_amount   DECIMAL(19,8) NOT NULL DEFAULT 0,
    split_coefficient DECIMAL(19,8) NOT NULL DEFAULT 1,
    UNIQUE (symbol, date, currency)
);

-- 배당
CREATE TABLE dividend (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol   VARCHAR(16)   NOT NULL,
    ex_date  DATE          NOT NULL,
    amount   DECIMAL(19,8) NOT NULL,
    currency VARCHAR(3)    NOT NULL DEFAULT 'USD',
    UNIQUE (symbol, ex_date)
);

-- 환율
CREATE TABLE fx_rate (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    currency_pair VARCHAR(7)    NOT NULL,
    date          DATE          NOT NULL,
    rate          DECIMAL(10,6) NOT NULL,
    UNIQUE (currency_pair, date)
);

-- 관리자 작업의 마지막 실행 기록 (V4)
CREATE TABLE admin_job_run (
    name        VARCHAR(64) PRIMARY KEY,
    last_run_at TIMESTAMP   NOT NULL,
    published   INTEGER     NOT NULL
);

-- ============================================================
-- 인덱스
-- ============================================================

-- candle
CREATE INDEX idx_candle_symbol_date      ON candle(symbol, date);
CREATE INDEX idx_candle_symbol_date_desc ON candle(symbol, date DESC);
CREATE INDEX idx_candle_dividend_lookup  ON candle(symbol, date, dividend_amount);

-- asset
CREATE INDEX idx_asset_country           ON asset(country);
CREATE INDEX idx_asset_currency          ON asset(currency);
CREATE INDEX idx_asset_type              ON asset(asset_type);
CREATE INDEX idx_asset_filters           ON asset(country, currency, asset_type);
CREATE INDEX idx_asset_active            ON asset(active);
CREATE INDEX idx_asset_active_filters    ON asset(active, country, asset_type);
CREATE INDEX idx_asset_market_cap        ON asset(market_cap DESC NULLS LAST);
CREATE INDEX idx_asset_active_market_cap ON asset(active, market_cap DESC NULLS LAST);

-- dividend: symbol + ex_date 는 UNIQUE 제약이 인덱스를 겸한다. V3 에서 중복분을 지웠다
CREATE INDEX idx_dividend_amount_date    ON dividend(amount DESC, ex_date);
CREATE INDEX idx_dividend_ex_date        ON dividend(ex_date);

-- fx_rate
CREATE INDEX idx_fx_rate_date            ON fx_rate(date);
CREATE INDEX idx_fx_rate_date_desc       ON fx_rate(date DESC);
CREATE INDEX idx_fx_rate_date_range      ON fx_rate(date, currency_pair);
