{{- if .Values.global.aws.secretsManager.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: config-server-credentials
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h  # 1시간마다 동기화
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: config-server-credentials
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.global.aws.secretsManager.name }}  # AWS Secrets Manager Secret 이름
        property: config_server_password  # JSON key
{{- end }}
