{{- if .Values.global.aws.secretsManager.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.global.aws.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: default
{{- end }}
