plugins {
    id 'java-platform'
    id 'maven-publish'
}

javaPlatform { allowDependencies() }

dependencies {
    api platform('org.springframework.boot:spring-boot-dependencies:3.5.4')
    api platform('org.springframework.cloud:spring-cloud-dependencies:2025.0.0')
    api platform('org.testcontainers:testcontainers-bom:1.20.1')
    
    constraints {
        // Core Libraries  
        api 'org.projectlombok:lombok:1.18.34'
        
        // Spring Cloud Config
        api 'org.springframework.cloud:spring-cloud-starter-config:4.1.3'
        api 'org.springframework.boot:spring-boot-starter-validation:3.5.4'
        
        // JWT
        api 'io.jsonwebtoken:jjwt-api:0.12.6'
        api 'io.jsonwebtoken:jjwt-impl:0.12.6'
        api 'io.jsonwebtoken:jjwt-jackson:0.12.6'
        
        // Database
        api 'org.postgresql:postgresql:42.7.4'
        api 'com.h2database:h2:2.3.232'
        api 'org.flywaydb:flyway-core:10.17.0'
        
        // Documentation
        api 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.6.0'
        api 'org.springdoc:springdoc-openapi-starter-webflux-ui:2.6.0'

        // QueryDSL
        api 'com.querydsl:querydsl-jpa:5.0.0:jakarta'
        api 'com.querydsl:querydsl-apt:5.0.0:jakarta'

        // Test
        api 'org.assertj:assertj-core:3.26.3'
        api 'org.mockito:mockito-core:5.13.0'
    }
}
tasks.register("prepareKotlinBuildScriptModel") { }
