{{- if .Values.frontend.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
  labels:
    app: {{ .Values.frontend.name }}
    {{- include "ggeolmuse.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.name }}
    spec:
      containers:
      - name: {{ .Values.frontend.name }}
        image: {{ include "ggeolmuse.image" (dict "Values" .Values "repository" .Values.frontend.image.repository "tag" .Values.frontend.image.tag "Chart" .Chart) }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.frontend.service.targetPort }}
        env:
        - name: VITE_API_URL
          value: {{ .Values.frontend.env.apiUrl | quote }}
        - name: VITE_KEYCLOAK_URL
          value: {{ .Values.frontend.env.keycloakUrl | quote }}
        - name: VITE_KEYCLOAK_REALM
          value: {{ .Values.frontend.env.keycloakRealm | quote }}
        - name: VITE_KEYCLOAK_CLIENT_ID
          value: {{ .Values.frontend.env.keycloakClientId | quote }}
{{- end }}
